### ISSUE TITLE
subsumed by i2b2 demodata?

### ISSUE THREAD

**Issue by dckc** [PCORnet/DECOY#2]
i2b2 comes with demodata... to what extent is DECOY re-inventing that wheel?

**Comment by jklann** [comment]
Actually, no... the i2b2 demodata is an artifact of a long-ago project, so we have no way to generate new demodata for new data elements... to have an approach to generate new data (for e.g., the PCORnet CDM ontology) would be really valuable.

**Comment by dckc** [comment]
Ah. Good to know.

**Comment by dckc** [comment]
@russwaitman Note Jeff's answer.

_If this were trac, I would have cc'd Russ; Let's see if @mention in github does the same job._

**Comment by bokov** [comment]
What data elements are missing from demodata that are needed by CDM?

Seems to me at least the demographics can be realistically generated, including covariance structure, by resampling with replacement from PATIENT_DIMENSION (and assigning random PATIENT_NUMs to each row of resampled data).

Also, what is the minimum set of features of the data are necessary for DECOY's purposes? Data in a star-schema? That plus realistic distributions of variables without considering their co-ocurrence (i.e. marginal distributions)? The previous two plus realistic co-ocurrence?

**Comment by dckc** [comment]
Alex, those are somewhat interesting questions, but I don't see anything in them that merits re-opening this issue. I see you opened #3 regarding DECOY's purposes. If follow-up on the others is something you'd like tracked, open issues for those as well.
