### ISSUE TITLE
Need well defined user stories.

### ISSUE THREAD

**Issue by bokov** [PCORnet/DECOY#3]
This project needs at least one user story describing who would be using the output of DECOY and for what purpose.

**Comment by dckc** [comment]
One goal that came up in chatting with @rwaitman is verification of tools to convert to CDM.

Suppose
- di() loads DECOY data into i2b2,
- oi() loads DECOY data into OMOP, and
-  g() transforms i2b2 to PCORnet CDM, and
-  h() transforms OMOP to PCORnet CDM.

Then given DECOY data d0, we (developers of conversion tools) could test that queries against g(di(d0)) give the same answers as h(oi(d0)).

And any time we find a bug or issue in g(), we should be able to represent it in DECOY and test whether it shows up in h(). And vice versa.

_TODO: migrate this user story to DECOY docs._

**Comment by bokov** [comment]
Do we use OMOP for anything? I was only aware of GPC using di(d0) and g(di(d0))

Also, what format is raw d0 going to be in? Clarity?

**Comment by dckc** [comment]
d0 is going to be in CSV format. That's the DECOY data.

GPC currently has no requirements to use OMOP, but OMOP has come up in the inter-CDRN [ModelMashUp](https://informatics.gpcnetwork.org/trac/Project/wiki/ModelMashUp) discussion as far back as Apr 2014, and as we expand our focus from GPC to the larger PCORnet community, its relevance increases.

The evolution of OMOP is OHDSI (pronounced like "odyssey"). The [OHDSI Guiding Principles](http://www.ohdsi.org/who-we-are/mission-vision-values/), especially the bits about transparency and open source, are pretty enticing. It's a community I'm interested to collaborate with.

**Comment by bokov** [comment]
> d0 is going to be in CSV format. That's the DECOY data. 

I guess I meant, what is the native data model of the DECOY data? I.e. how are patients, visits, and facts represented? In one CSV file or in several? What columns will exist? Does anything except DECOY emit data structured in that manner?

**Comment by dckc** [comment]
Those questions represent a large part of the design space of DECOY; none of them is settled.

**Comment by bokov** [comment]
Well, if we're going to write an ETL for a completely new datasource none of us use, I nominate the OpenEMR data model. In fact, IIRC they may already have simulated data that will save us the trouble.

**Comment by dckc** [comment]
Good idea; merits its own issue.

I think the github workflow might help if you open it. I'll stand by, and if you don't get around to it, I can do it.

**Comment by dckc** [comment]
Do you mean [OpenMRS](http://openmrs.org/)?

**Comment by bokov** [comment]
Sure, them too, why not?

Looks like they have a standalone dataset.

**Comment by bokov** [comment]
And then there's VistA (the VA EMR, which is also open-source). Took a while to find the useful page, but here it is:
https://www.osehra.org/content/distributions-vista

Apparently a bunch of forks to choose from, yay.

**Comment by dckc** [comment]
DECOY came up in a chat with @russwaitman and he elaborated on motivation; see [ETL cross-checking](https://github.com/PCORnet/DECOY/wiki#etl-cross-checking).

It's similar to the `g(di(d0))` discussion above, but more clear I think.
